---
title: "Resume"
output: html_document
date: "2019-12-15"
---

```

## Jarrett Rong
### Email: jrong97@gmail.com
### Education: BSA Biology, The University of Texas at Austin
#### About: Pre-medical student at UT Austin pursuing a major in biology and minor in entrepreneurship. In my free time, I enjoy hiking and cooking.
#### Skills: Molecular biology lab techniques, basic coding in R, public speaking, new venture mechanics.

> Work Experiences

* Freshman Research Initiative at UT Austin
  + Functional Genomics lab from 2017-2019
* St. Jude Children's Research Hospital
  + Labs of Dr. Jian Zuo and Dr. William Evans in summer of 2017 and 2019 respectively.

> Leadership

* UT Health Science Scholars Council
  + Social Committee
  + Elected president in 2018
* UT Natural Sciences Council
  + Internal Relations
  + Appointed Internal Relations chair in 2017
* Texas Model United Nations
  + Moderator for high school students competing from across the country.
* Dell Children's Medical Center
  + Volunteer in the Children's Blood and Cancer Center
  
> Accomplishments

* University Honors
  + 2017-2019
